name: Daily WhatsApp Reminder

on:
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 9:30 AM IST (4:00 AM UTC)
  workflow_dispatch:      # Allows manual trigger from Actions tab

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Run WhatsApp Reminder App
        run: java -cp target/WhatsAppReminderRotating-1.0-SNAPSHOT.jar WhatsAppReminderRotating
